# Generated by Django 3.2 on 2022-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='y',
            field=models.FloatField(),
        ),
    ]
