# Generated by Django 4.0.4 on 2022-04-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo_url',
            field=models.CharField(max_length=200),
        ),
    ]
