# Generated by Django 3.2 on 2022-04-21 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gallery_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='landmark',
            field=models.ForeignKey(db_column='landmark_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.landmark'),
            preserve_default=False,
        ),
    ]
